=== sanyaade-teachings/securicad-model-sdk/securicad/model/model.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/foreseeti/securicad-model-sdk/master/securicad/model/model.schema.json",
  "title": "jsonmodelschema",
  "description": "",
  "definitions": {
    "int64": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9223372036854776000
    },
    "identifier": {
      "type": "string",
      "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
    },
    "field": {
      "type": "string",
      "pattern": "^[A-Za-z_][A-Za-z0-9_]*(\\.attacker)?$"
    },
    "ttcExpression": {
      "$comment": "Taken from https://raw.githubusercontent.com/mal-lang/mal-langspec/master/src/main/resources/org/mal_lang/langspec/lang.schema.json",
      "allOf": [
        {
          "type": "object",
          "properties": {
            "type": {
              "enum": [
                "addition",
                "subtraction",
                "multiplication",
                "division",
                "exponentiation",
                "function",
                "number"
              ]
            }
          },
          "required": [
            "type"
          ]
        },
        {
          "if": {
            "properties": {
              "type": {
                "enum": [
                  "addition",
                  "subtraction",
                  "multiplication",
                  "division",
                  "exponentiation"
                ]
              }
            }
          },
          "then": {
            "properties": {
              "type": true,
              "lhs": {
                "$ref": "#/definitions/ttcExpression"
              },
              "rhs": {
                "$ref": "#/definitions/ttcExpression"
              }
            },
            "additionalProperties": false,
            "required": [
              "lhs",
              "rhs"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "function"
              }
            }
          },
          "then": {
            "properties": {
              "type": true,
              "name": {
                "$ref": "#/definitions/identifier"
              },
              "arguments": {
                "type": "array",
                "items": {
                  "type": "number"
                }
              }
            },
            "additionalProperties": false,
            "required": [
              "name",
              "arguments"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "number"
              }
            }
          },
          "then": {
            "properties": {
              "type": true,
              "value": {
                "type": "number"
              }
            },
            "additionalProperties": false,
            "required": [
              "value"
            ]
          }
        }
      ]
    },
    "meta": {
      "type": "object"
    },
    "modelmeta": {
      "type": "object",
      "properties": {
        "langId": {
          "type": "string"
        },
        "langVersion": {
          "type": "string",
          "pattern": "^\\d+\\.\\d+\\.\\d+$"
        }
      },
      "required": [
        "langId",
        "langVersion"
      ]
    },
    "object": {
      "type": "object",
      "properties": {
        "meta": {
          "$ref": "#/definitions/meta"
        },
        "name": {
          "type": "string"
        },
        "id": {
          "$ref": "#/definitions/int64"
        },
        "asset_type": {
          "$ref": "#/definitions/identifier"
        },
        "attack_steps": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/attack_step"
          }
        },
        "defenses": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/defense"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "id",
        "asset_type",
        "attack_steps",
        "defenses"
      ]
    },
    "attack_step": {
      "type": "object",
      "properties": {
        "meta": {
          "$ref": "#/definitions/meta"
        },
        "name": {
          "$ref": "#/definitions/identifier"
        },
        "ttc": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/ttcExpression"
            }
          ]
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "ttc"
      ]
    },
    "defense": {
      "type": "object",
      "properties": {
        "meta": {
          "$ref": "#/definitions/meta"
        },
        "name": {
          "$ref": "#/definitions/identifier"
        },
        "probability": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "type": "number",
              "minimum": 0,
              "maximum": 1
            }
          ]
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "probability"
      ]
    },
    "association": {
      "type": "object",
      "properties": {
        "meta": {
          "$ref": "#/definitions/meta"
        },
        "source_object_id": {
          "$ref": "#/definitions/int64"
        },
        "source_field": {
          "$ref": "#/definitions/field"
        },
        "target_object_id": {
          "$ref": "#/definitions/int64"
        },
        "target_field": {
          "$ref": "#/definitions/field"
        }
      },
      "additionalProperties": false,
      "required": [
        "source_object_id",
        "source_field",
        "target_object_id",
        "target_field"
      ]
    },
    "view": {
      "type": "object",
      "properties": {
        "meta": {
          "$ref": "#/definitions/meta"
        },
        "name": {
          "type": "string"
        },
        "id": {
          "$ref": "#/definitions/int64"
        },
        "items": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "$ref": "#/definitions/view_object"
              },
              {
                "$ref": "#/definitions/view_group"
              }
            ]
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "id",
        "items"
      ]
    },
    "view_object": {
      "type": "object",
      "properties": {
        "meta": {
          "$ref": "#/definitions/meta"
        },
        "type": {
          "const": "object"
        },
        "id": {
          "$ref": "#/definitions/int64"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "additionalProperties": false,
      "required": [
        "type",
        "id",
        "x",
        "y"
      ]
    },
    "view_group": {
      "type": "object",
      "properties": {
        "meta": {
          "$ref": "#/definitions/meta"
        },
        "type": {
          "const": "group"
        },
        "name": {
          "type": "string"
        },
        "id": {
          "$ref": "#/definitions/int64"
        },
        "icon": {
          "type": "string"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "items": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "$ref": "#/definitions/view_object"
              },
              {
                "$ref": "#/definitions/view_group"
              }
            ]
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "type",
        "name",
        "id",
        "icon",
        "x",
        "y",
        "items"
      ]
    },
    "icon": {
      "type": "object",
      "properties": {
        "meta": {
          "$ref": "#/definitions/meta"
        },
        "name": {
          "type": "string"
        },
        "format": {
          "type": "string"
        },
        "data": {
          "type": "string",
          "contentEncoding": "base64"
        },
        "license": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "format",
        "data",
        "license"
      ]
    }
  },
  "type": "object",
  "properties": {
    "meta": {
      "$ref": "#/definitions/modelmeta"
    },
    "name": {
      "type": "string"
    },
    "objects": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/object"
      }
    },
    "associations": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/association"
      }
    },
    "views": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/view"
      }
    },
    "icons": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/icon"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "name",
    "objects",
    "associations",
    "views",
    "icons"
  ]
}

=== sanyaade-teachings/securicad-model-sdk/tests/model/model3.json
{
  "name": "unnamed",
  "meta": {
    "langId": "null",
    "langVersion": "0.0.0"
  },
  "objects": [
    {
      "meta": {},
      "id": 1,
      "name": "ecu1",
      "asset_type": "ECU",
      "attack_steps": [
        {
          "meta": {},
          "name": "att",
          "ttc": {
            "type": "number",
            "value": 1
          }
        }
      ],
      "defenses": [
        {
          "meta": {},
          "name": "def",
          "probability": 0.3
        }
      ]
    },
    {
      "meta": {},
      "id": 2,
      "name": "ecu2",
      "asset_type": "ECU",
      "attack_steps": [],
      "defenses": []
    },
    {
      "meta": {},
      "id": 3,
      "name": "ecu3",
      "asset_type": "ECU",
      "attack_steps": [],
      "defenses": []
    },
    {
      "meta": {},
      "id": 4,
      "name": "Attacker",
      "asset_type": "Attacker",
      "attack_steps": [],
      "defenses": []
    },
    {
      "meta": {},
      "id": 8,
      "name": "firmware",
      "asset_type": "Firmware",
      "attack_steps": [],
      "defenses": []
    },
    {
      "meta": {},
      "id": 9,
      "name": "",
      "asset_type": "Unknown",
      "attack_steps": [],
      "defenses": []
    }
  ],
  "associations": [
    {
      "meta": {},
      "source_object_id": 1,
      "source_field": "firmware",
      "target_object_id": 8,
      "target_field": "hardware"
    },
    {
      "meta": {},
      "source_object_id": 2,
      "source_field": "firmware",
      "target_object_id": 8,
      "target_field": "hardware"
    },
    {
      "meta": {},
      "source_object_id": 3,
      "source_field": "firmware",
      "target_object_id": 8,
      "target_field": "hardware"
    },
    {
      "meta": {},
      "source_object_id": 4,
      "source_field": "firstSteps",
      "target_object_id": 1,
      "target_field": "access.attacker"
    },
    {
      "meta": {},
      "source_object_id": 8,
      "source_field": "from",
      "target_object_id": 1,
      "target_field": "to"
    }
  ],
  "views": [
    {
      "meta": {},
      "id": 5,
      "name": "default",
      "items": [
        {
          "meta": {},
          "id": 6,
          "name": "g",
          "items": [
            {
              "meta": {},
              "id": 7,
              "name": "g",
              "items": [],
              "x": 0,
              "y": 0,
              "icon": "?",
              "type": "group"
            }
          ],
          "x": 0,
          "y": 0,
          "icon": "?",
          "type": "group"
        }
      ]
    }
  ],
  "icons": []
}

=== sanyaade-teachings/securicad-model-sdk/tests/model/model5.json
{
  "name": "unnamed",
  "meta": {
    "langId": "com.foreseeti.securilang",
    "langVersion": "2.1.9",
    "samples": 999,
    "warningThreshold": 99
  },
  "objects": [
    {
      "meta": {
        "description": "",
        "existence": 1
      },
      "id": 1,
      "name": "Attacker",
      "asset_type": "Attacker",
      "attack_steps": [],
      "defenses": []
    },
    {
      "meta": {
        "description": "",
        "existence": 1
      },
      "id": 2,
      "name": "Client",
      "asset_type": "Client",
      "attack_steps": [
        {
          "meta": {
            "description": ""
          },
          "name": "patched",
          "ttc": null
        }
      ],
      "defenses": [
        {
          "meta": {},
          "name": "patched",
          "probability": 0.37
        }
      ]
    },
    {
      "meta": {
        "description": "",
        "existence": 1
      },
      "id": 3,
      "name": "SoftwareProduct",
      "asset_type": "SoftwareProduct",
      "attack_steps": [
        {
          "meta": {
            "description": ""
          },
          "name": "developZeroDay",
          "ttc": {
            "type": "function",
            "name": "Gamma",
            "arguments": [
              1.4,
              0.6
            ]
          }
        }
      ],
      "defenses": []
    },
    {
      "meta": {
        "description": "",
        "existence": 1
      },
      "id": 4,
      "name": "SoftwareProduct",
      "asset_type": "SoftwareProduct",
      "attack_steps": [],
      "defenses": []
    },
    {
      "meta": {
        "tags": {
          "server": "tag"
        },
        "description": "",
        "existence": 1
      },
      "id": 5,
      "name": "Host",
      "asset_type": "Host",
      "attack_steps": [
        {
          "meta": {
            "description": "",
            "consequence": 1
          },
          "name": "compromise",
          "ttc": null
        }
      ],
      "defenses": []
    }
  ],
  "associations": [
    {
      "meta": {},
      "source_object_id": 1,
      "source_field": "firstSteps",
      "target_object_id": 2,
      "target_field": "compromise.attacker"
    },
    {
      "meta": {},
      "source_object_id": 2,
      "source_field": "rootHost",
      "target_object_id": 5,
      "target_field": "rootClients"
    },
    {
      "meta": {},
      "source_object_id": 3,
      "source_field": "clients",
      "target_object_id": 2,
      "target_field": "softwareProduct"
    },
    {
      "meta": {},
      "source_object_id": 5,
      "source_field": "softwareProduct",
      "target_object_id": 4,
      "target_field": "hosts"
    }
  ],
  "views": [
    {
      "meta": {
        "loadOnStart": true
      },
      "id": 6,
      "name": "High Value Assets",
      "items": [
        {
          "meta": {},
          "id": 1,
          "x": 182,
          "y": 92,
          "type": "object"
        },
        {
          "meta": {
            "color": "#4caf50",
            "expand": false,
            "description": "Client group!"
          },
          "id": 2648631069477343,
          "name": "Client",
          "items": [
            {
              "meta": {},
              "id": 2,
              "x": 1,
              "y": -88,
              "type": "object"
            },
            {
              "meta": {},
              "id": 3,
              "x": 32,
              "y": 94,
              "type": "object"
            }
          ],
          "x": 352,
          "y": 295,
          "icon": "radar",
          "type": "group"
        },
        {
          "meta": {
            "color": "#03a9f4",
            "expand": true,
            "tags": {
              "server": "tag"
            },
            "description": ""
          },
          "id": 9049883380945900,
          "name": "Encap",
          "items": [
            {
              "meta": {
                "color": "#e91e63",
                "expand": true,
                "description": "This is the server group."
              },
              "id": 3659407383211753,
              "name": "Server",
              "items": [
                {
                  "meta": {},
                  "id": 5,
                  "x": -7,
                  "y": -75,
                  "type": "object"
                },
                {
                  "meta": {},
                  "id": 4,
                  "x": 163,
                  "y": 79,
                  "type": "object"
                }
              ],
              "x": 1,
              "y": 17,
              "icon": "IPS",
              "type": "group"
            }
          ],
          "x": 675,
          "y": 242,
          "icon": "PhysicalZone",
          "type": "group"
        }
      ]
    },
    {
      "meta": {
        "loadOnStart": true
      },
      "id": 7,
      "name": "High Value Assets",
      "items": [
        {
          "meta": {},
          "id": 5,
          "x": 0,
          "y": 0,
          "type": "object"
        }
      ]
    }
  ],
  "icons": []
}

=== sanyaade-teachings/securicad-model-sdk/tests/model/model2.json
{
  "name": "unnamed",
  "meta": {
    "langId": "org.mal-lang.vehiclelang",
    "langVersion": "1.0.0"
  },
  "objects": [
    {
      "meta": {
        "existence": 1
      },
      "id": 1,
      "name": "ECU",
      "asset_type": "ECU",
      "attack_steps": [
        {
          "meta": {
            "consequence": 2
          },
          "name": "shutdown",
          "ttc": null
        }
      ],
      "defenses": []
    },
    {
      "meta": {
        "existence": 1
      },
      "id": 2,
      "name": "Attacker",
      "asset_type": "Attacker",
      "attack_steps": [],
      "defenses": []
    }
  ],
  "associations": [
    {
      "meta": {},
      "target_object_id": 2,
      "target_field": "firstSteps",
      "source_object_id": 1,
      "source_field": "access.attacker"
    }
  ],
  "views": [],
  "icons": []
}

=== sanyaade-teachings/securicad-model-sdk/tests/model/model1.json
{
  "name": "unnamed",
  "meta": {
    "langId": "org.mal-lang.vehiclelang",
    "langVersion": "1.0.0"
  },
  "objects": [
    {
      "meta": {},
      "id": 1,
      "name": "Base ECU",
      "asset_type": "ECU",
      "attack_steps": [
        {
          "meta": {},
          "name": "shutdown",
          "ttc": {
            "type": "number",
            "value": 2
          }
        },
        {
          "meta": {},
          "name": "access",
          "ttc": {
            "type": "division",
            "lhs": {
              "type": "addition",
              "lhs": {
                "type": "function",
                "name": "Exponential",
                "arguments": [
                  0.6
                ]
              },
              "rhs": {
                "type": "number",
                "value": 5
              }
            },
            "rhs": {
              "type": "number",
              "value": 12
            }
          }
        }
      ],
      "defenses": [
        {
          "meta": {
            "dsiabled": true
          },
          "name": "operationModeProtection",
          "probability": 0.5
        }
      ]
    },
    {
      "meta": {},
      "id": 2,
      "name": "Attacker",
      "asset_type": "Attacker",
      "attack_steps": [],
      "defenses": []
    },
    {
      "meta": {
        "my_tag": true
      },
      "id": 3,
      "name": "",
      "asset_type": "Firmware",
      "attack_steps": [],
      "defenses": []
    }
  ],
  "associations": [
    {
      "meta": {},
      "source_object_id": 2,
      "source_field": "firstSteps",
      "target_object_id": 1,
      "target_field": "access.attacker"
    },
    {
      "meta": {},
      "source_object_id": 3,
      "source_field": "hardware",
      "target_object_id": 1,
      "target_field": "firmware"
    }
  ],
  "views": [
    {
      "meta": {},
      "id": 4,
      "name": "default",
      "items": [
        {
          "meta": {},
          "id": 3,
          "x": 0,
          "y": 0,
          "type": "object"
        },
        {
          "meta": {
            "color": [
              255,
              0,
              0
            ]
          },
          "id": 5,
          "name": "Group",
          "items": [
            {
              "meta": {},
              "id": 1,
              "x": 0,
              "y": 0,
              "type": "object"
            }
          ],
          "x": 0,
          "y": 0,
          "icon": "Icon",
          "type": "group"
        }
      ]
    }
  ],
  "icons": [
    {
      "name": "Icon",
      "license": "license",
      "data": "iVBORw0KGgo=",
      "format": "png",
      "meta": {}
    }
  ]
}

=== sanyaade-teachings/securicad-model-sdk/tests/model/model7.json
{
  "name": "unnamed",
  "meta": {
    "langId": "null",
    "langVersion": "0.0.0"
  },
  "objects": [
    {
      "meta": {},
      "id": 1,
      "name": "ecu",
      "asset_type": "ECU",
      "attack_steps": [],
      "defenses": []
    },
    {
      "meta": {},
      "id": 2,
      "name": "ecu",
      "asset_type": "ECU",
      "attack_steps": [],
      "defenses": []
    },
    {
      "meta": {},
      "id": 4,
      "name": "ecu",
      "asset_type": "ECU",
      "attack_steps": [],
      "defenses": []
    }
  ],
  "associations": [],
  "views": [
    {
      "meta": {},
      "id": 5,
      "name": "default",
      "items": [
        {
          "meta": {},
          "id": 3455436,
          "name": "g",
          "items": [
            {
              "meta": {},
              "id": 6,
              "name": "g",
              "items": [],
              "x": 0,
              "y": 0,
              "icon": "?",
              "type": "group"
            }
          ],
          "x": 0,
          "y": 0,
          "icon": "?",
          "type": "group"
        }
      ]
    }
  ],
  "icons": []
}
